Marcin/extract
mknorps/RAG-exeperiment pull request #16
Opened 2024-04-25 06:59 UTC by marcin-zadrozny

Added functions to extract.py to find Arxiv papers and extract their .tex files.

2024-04-25 07:35 UTC, mknorps requested changes
Works well at the current stage :rocket: 

I would like to ask you though to add metadata to the data you are downloading from ArXiv.
Each folder should contain a json file called `metadata.json` containing all available metadata given by ArXiv, in particular:
- author's name
- title of the publication
- date of the publication
- domain
- tags

2024-04-29 08:18 UTC, marcin-zadrozny commented on rag_experiment/extract.py
Not sure if I should include all the other metadata (entry_id, update date etc.), added the requested ones for now.

2024-05-16 07:13 UTC, mknorps commented on rag_experiment/extract.py
`entry_id` may be useful for as as a unique identifier of an ArXiv article

2024-05-22 16:37 UTC, mknorps approved these changes
LGTM :rocket:

2024-05-22 16:37 UTC, mknorps commented on rag_experiment/extract.py
> +    for i, file_name in enumerate(os.listdir(source_dir)):
```suggestion
    for file_name in os.listdir(source_dir):
```
No need for enumeration. We do not use this `i` anyway..

2024-05-23 07:23 UTC, merged